name: KiBot Check Base

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
      config-file:
        required: true
        type: string

jobs:
  change-check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - '.github/workflows/ci.yml'
              - '.github/workflows/kibot-check-base.yml'
              - 'kibot.yml'
              - '${{ inputs.folder }}/*.kicad_{pcb,pro,sch}"'

  ERC:
    runs-on: ubuntu-latest
    needs: change-check
    if: needs.change-check.outputs.changed == 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Run ERC
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          dir: Generated/${{ inputs.folder }}
          config: kibot.yml
          board: ${{ inputs.config-file }}
          skip: run_drc
          targets: __NONE__

      - name: Retrieve results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.folder }}_ERC_Output
          path: Generated/${{ inputs.folder }}

  DRC:
    runs-on: ubuntu-latest
    needs: [ERC, change-check]
    if: needs.change-check.outputs.changed == 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Run DRC
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          dir: Generated/${{ inputs.folder }}
          config: kibot.yml
          board: ${{ inputs.config-file }}
          skip: run_erc
          targets: __NONE__

      - name: Retrieve results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.folder }}_DRC_Output
          path: Generated/${{ inputs.folder }}
