name: KiBot Base

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
      config-file:
        required: true
        type: string
    secrets:
      DOCS_DEPLOY_KEY:
        required: true

jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ERC
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          dir: Generated
          config: kibot.yml
          board: ${{ inputs.config-file }}
          skip: run_drc
          targets: __NONE__

      - name: Retrieve results
        uses: actions/upload-artifact@v3
        with:
          name: ERC_Output
          path: Generated

  DRC:
    runs-on: ubuntu-latest
    needs: ERC

    steps:
      - uses: actions/checkout@v3

      - name: Run DRC
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          dir: Generated
          config: kibot.yml
          board: ${{ inputs.config-file }}
          skip: run_erc
          targets: __NONE__

      - name: Retrieve results
        uses: actions/upload-artifact@v3
        with:
          name: DRC_Output
          path: Generated

  Render:
    name: "Render"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
      - uses: actions/checkout@v3

      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          dir: Render
          config: kibot.yml
          board: ${{ inputs.config-file }}
          skip: all

      - name: upload results
        uses: actions/upload-artifact@v3
        with:
          name: Render
          path: Render

      - name: deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Render
          ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
          branch: main
          repository-name: bloop-box/bloop-box-hardware-docs
          target-folder: ${{ inputs.folder }}
