name: KiBot Base

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string

jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ERC
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          kicad: 5
          dir: Generated
          config: kibot.yml
          board: ${{ inputs.dir }}/*.kicad_pcb
          skip: run_drc
          targets: __NONE__

      - name: Retrieve results
        uses: actions/upload-artifact@v3
        with:
          name: ERC_Output
          path: Generated

  DRC:
    runs-on: ubuntu-latest
    needs: ERC

    steps:
      - uses: actions/checkout@v3

      - name: Run DRC
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          kicad: 5
          dir: Generated
          config: kibot.yml
          board: ${{ inputs.dir }}/*.kicad_pcb
          skip: run_erc
          targets: __NONE__

      - name: Retrieve results
        uses: actions/upload-artifact@v3
        with:
          name: DRC_Output
          path: Generated

  Render:
    name: "Render"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
      - uses: actions/checkout@v3

      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          kicad: 5
          dir: Render
          config: kibot.yml
          board: ${{ inputs.dir }}/*.kicad_pcb
          skip: all

      - name: upload results
        uses: actions/upload-artifact@v3
        with:
          name: Render
          path: Render
