name: Pull Request

on:
  pull_request:
    paths:
      - "pcb/*.kicad_*"
      - "kibot.yml"
      - ".github/workflows/pull-request.yml"

jobs:
  check:
    name: Check
    uses: bloop-box/reusable-workflows/.github/workflows/kibot-check.yml@main
    with:
      config-file: kibot.yml
      board-file: pcb/BloopBox Mainboard.kicad_pcb
